server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
#      基于配置文件的路由
      routes:
        - id: baidu
          filters:
            - StripPrefix=1
          uri: https://www.baidu.cn
          predicates:
            - Path=/baidu
        - id: qq
          uri: https://www.qq.com
          predicates:
            - Path=/qq
          filters:
            - StripPrefix=1
#      基于注册中心的动态路由获取，会自动将注册中心中的服务创建路由
      discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: 192.168.209.128:8848

